using QuantTrader.Common.Enums;

namespace QuantTrader.Common.Models;

/// <summary>Represents a trade signal generated by a strategy engine.</summary>
public sealed record TradeSignal(
    Guid Id,
    string Symbol,
    TradeAction Action,
    decimal Quantity,
    decimal? Price,
    decimal? StopLoss,
    decimal? TakeProfit,
    string Strategy,
    double ConfidenceScore,
    DateTimeOffset Timestamp,
    string CorrelationId);
